export const INIT = 'INIT';
export const SET_ERROR = 'SET_ERROR';
export const SET_CURRENTLY_EDITING_ID = 'SET_CURRENTLY_EDITING_ID';
export const APPEND_MANAGER = 'APPEND_MANAGER';
export const UPDATE_MANAGER = 'UPDATE_MANAGER';
export const DELETE_MANAGER = 'DELETE_MANAGER';
export const APPEND_PROJECT = 'APPEND_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const APPEND_DEVELOPER = 'APPEND_DEVELOPER';
export const UPDATE_DEVELOPER = 'UPDATE_DEVELOPER';
export const MOVE_DEVELOPER = 'MOVE_DEVELOPER';

export type Type =
  | 'INIT'
  | 'SET_ERROR'
  | 'SET_CURRENT'
  | 'SET_CURRENTLY_EDITING_ID'
  | 'APPEND_MANAGER'
  | 'UPDATE_MANAGER'
  | 'DELETE_MANAGER'
  | 'APPEND_PROJECT'
  | 'UPDATE_PROJECT'
  | 'DELETE_PROJECT'
  | 'APPEND_DEVELOPER'
  | 'DELETE_DEVELOPER'
  | 'UPDATE_DEVELOPER'
  | 'MOVE_DEVELOPER';
